# Generated by Django 5.1.5 on 2025-02-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minio_doc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default=1, upload_to='media_files/'),
            preserve_default=False,
        ),
    ]
